import { CarouselData, CarouselTheme, TopicPreset } from "../types/carousel";

export const THEMES: Record<string, CarouselTheme> = {
  "luxury-gold": {
    id: "luxury-gold",
    name: "Gilded Amber",
    description: "Deep obsidian canvas with warm amber & gold metallic accents",
    backgroundClass: "bg-gradient-to-br from-stone-950 via-stone-900 to-amber-950/30 text-stone-100",
    canvasBg: "#0c0a09",
    canvasTextPrimary: "#f5f5f4",
    canvasTextSecondary: "#a8a29e",
    canvasAccent: "#f59e0b",
    canvasCardBg: "#1c1917",
    textPrimaryClass: "text-stone-100",
    textSecondaryClass: "text-stone-400",
    accentClass: "text-amber-400",
    badgeClass: "bg-amber-500/15 border border-amber-500/30 text-amber-300",
    cardBgClass: "bg-stone-900/80 border border-stone-800/80",
    fontHeading: "serif",
    accentBorder: "border-amber-500/30",
  },
  "botanical-sage": {
    id: "botanical-sage",
    name: "Artisan Sage",
    description: "Earthy olive & sage tones with warm terracotta accents",
    backgroundClass: "bg-gradient-to-br from-[#121c16] via-[#16231c] to-[#0f1712] text-stone-100",
    canvasBg: "#121c16",
    canvasTextPrimary: "#f2f5f3",
    canvasTextSecondary: "#99ab9f",
    canvasAccent: "#5eead4",
    canvasCardBg: "#1a2920",
    textPrimaryClass: "text-stone-100",
    textSecondaryClass: "text-emerald-300/70",
    accentClass: "text-emerald-400",
    badgeClass: "bg-emerald-500/15 border border-emerald-500/30 text-emerald-300",
    cardBgClass: "bg-[#18261e]/80 border border-[#263c30]",
    fontHeading: "modern",
    accentBorder: "border-emerald-500/30",
  },
  "midnight-velvet": {
    id: "midnight-velvet",
    name: "Midnight Velvet",
    description: "Ultra-dark luxury violet with subtle glowing borders",
    backgroundClass: "bg-gradient-to-br from-[#090714] via-[#120e24] to-[#06040d] text-stone-100",
    canvasBg: "#090714",
    canvasTextPrimary: "#f5f3ff",
    canvasTextSecondary: "#a78bfa",
    canvasAccent: "#c084fc",
    canvasCardBg: "#17122e",
    textPrimaryClass: "text-purple-50",
    textSecondaryClass: "text-purple-300/70",
    accentClass: "text-purple-400",
    badgeClass: "bg-purple-500/15 border border-purple-500/30 text-purple-300",
    cardBgClass: "bg-[#150f2e]/80 border border-purple-900/40",
    fontHeading: "luxury",
    accentBorder: "border-purple-500/30",
  },
  "editorial-stone": {
    id: "editorial-stone",
    name: "Minimalist Ivory",
    description: "High-contrast editorial style with clean limestone tones",
    backgroundClass: "bg-gradient-to-br from-[#1c1b18] via-[#24221e] to-[#171614] text-stone-100",
    canvasBg: "#1c1b18",
    canvasTextPrimary: "#fcfbf7",
    canvasTextSecondary: "#b8b4a8",
    canvasAccent: "#e5e0d0",
    canvasCardBg: "#292722",
    textPrimaryClass: "text-stone-100",
    textSecondaryClass: "text-stone-400",
    accentClass: "text-amber-200",
    badgeClass: "bg-stone-800 border border-stone-700 text-stone-200",
    cardBgClass: "bg-stone-900/90 border border-stone-800",
    fontHeading: "serif",
    accentBorder: "border-stone-600",
  },
  "blush-rose": {
    id: "blush-rose",
    name: "Rose Champagne",
    description: "Soft romantic blush & warm champagne elegance",
    backgroundClass: "bg-gradient-to-br from-[#1d1217] via-[#291720] to-[#140b0f] text-rose-50",
    canvasBg: "#1d1217",
    canvasTextPrimary: "#fff1f2",
    canvasTextSecondary: "#f43f5e",
    canvasAccent: "#fb7185",
    canvasCardBg: "#2d1b24",
    textPrimaryClass: "text-rose-50",
    textSecondaryClass: "text-rose-300/70",
    accentClass: "text-rose-400",
    badgeClass: "bg-rose-500/15 border border-rose-500/30 text-rose-300",
    cardBgClass: "bg-[#28151f]/80 border border-rose-900/40",
    fontHeading: "serif",
    accentBorder: "border-rose-500/30",
  },
  "royal-sapphire": {
    id: "royal-sapphire",
    name: "Royal Sapphire",
    description: "Deep oceanic blue with icy silver and cyan highlights",
    backgroundClass: "bg-gradient-to-br from-[#06121f] via-[#0b1d30] to-[#040c14] text-sky-50",
    canvasBg: "#06121f",
    canvasTextPrimary: "#f0f9ff",
    canvasTextSecondary: "#7dd3fc",
    canvasAccent: "#38bdf8",
    canvasCardBg: "#0f263e",
    textPrimaryClass: "text-sky-50",
    textSecondaryClass: "text-sky-300/70",
    accentClass: "text-sky-400",
    badgeClass: "bg-sky-500/15 border border-sky-500/30 text-sky-300",
    cardBgClass: "bg-[#0b1f33]/80 border border-sky-800/40",
    fontHeading: "modern",
    accentBorder: "border-sky-500/30",
  },
};

export const INITIAL_TOPIC_PRESETS: TopicPreset[] = [
  {
    id: "luxury-hampers",
    title: "5 Luxury Gift Hampers That Make Anyone Feel Deeply Cherished",
    category: "Luxury Hampers",
    hook: "Most hampers end up in dusty pantry shelves. These 5 leave people speechless.",
    angle: "Curated Luxury",
    slidesCount: 6,
  },
  {
    id: "person-who-has-everything",
    title: "What to Gift the Person Who Has Everything (Without Buying Clutter)",
    category: "Thoughtful & Unique",
    hook: "Stop buying generic scented candles. Use this 3-question gifting test.",
    angle: "High Curiosity",
    slidesCount: 5,
  },
  {
    id: "last-minute-thoughtful",
    title: "4 Last-Minute Gifts That Look Like You Planned Them Months Ago",
    category: "Quick Solutions",
    hook: "Forgot an important date? Here's how to look like the most thoughtful person alive.",
    angle: "Urgency & Relief",
    slidesCount: 5,
  },
  {
    id: "corporate-memorable",
    title: "Corporate Gifting Etiquette: Gifts Clients Actually Keep & Love",
    category: "Corporate & Work",
    hook: "Why 80% of client merchandise gets tossed—and 3 gifts that build loyalty.",
    angle: "Professional Insight",
    slidesCount: 6,
  },
  {
    id: "anniversary-formula",
    title: "The 3-Part Surprise Formula for Unforgettable Anniversary Gifting",
    category: "Romantic & Couple",
    hook: "The secret to gifts that bring happy tears isn't the price tag—it's this formula.",
    angle: "Emotional Storytelling",
    slidesCount: 5,
  },
  {
    id: "budget-chic",
    title: "7 Aesthetic Gifts Under $40 That Look Like a Million Bucks",
    category: "Budget Chic",
    hook: "You don't need a luxury budget to deliver an undeniably upscale experience.",
    angle: "High Value",
    slidesCount: 6,
  },
  {
    id: "unboxing-experience",
    title: "How to Turn Any Simple Present Into a 10/10 Unboxing Experience",
    category: "Presentation & Style",
    hook: "The magic happens before they even open the box. 4 unboxing rules.",
    angle: "Visual Aesthetic",
    slidesCount: 5,
  },
  {
    id: "return-gifts-modern",
    title: "Modern Return Gifts for Parties: What Guests Really Appreciate",
    category: "Host & Events",
    hook: "No more plastic trinkets. Here is what party hosts are curating in 2026.",
    angle: "Event Trends",
    slidesCount: 5,
  },
];

export const INITIAL_CAROUSEL: CarouselData = {
  title: "5 Luxury Gift Hampers That Make Anyone Feel Deeply Cherished",
  themeSuggestion: "luxury-gold",
  keyTakeaway: "A great gift connects emotionally and elevates the everyday sensory routine.",
  websiteUrl: "https://snazzy-gnome-1d4893.netlify.app/gifts",
  brandName: "Snazzy Gnome Gifts",
  brandHandle: "@snazzygnomegifts",
  slides: [
    {
      slideNumber: 1,
      type: "cover",
      eyebrow: "CURATED GIFTING GUIDE",
      headline: "5 Luxury Gift Hampers That Make Anyone Feel Deeply Cherished",
      subheadline: "Stop gifting forgettable generic baskets. Here is how to create unboxing wonder.",
      body: "Whether it is an anniversary, milestone birthday, or client milestone, these 5 bespoke gift pairings turn any celebration into an unforgettable memory.",
      swipePrompt: "Swipe to discover ➔",
      highlightBadge: "Curator's Edit",
    },
    {
      slideNumber: 2,
      type: "content",
      eyebrow: "01 · THE RELAXATION SANCTUARY",
      headline: "The Artisan Spa & Restoration Hamper",
      subheadline: "For the friend or partner who is constantly carrying the world's weight.",
      body: "Pair small-batch mineral bath soaks, hand-poured beeswax candles, a weighted linen eye pillow, and botanical herbal infusions.",
      bulletPoints: [
        "Include handwritten fragrance notes for sensory immersion",
        "Select calming organic lavender and cedarwood accords",
        "Add reusable ceramic vessel for long-term daily remembrance"
      ],
      highlightBadge: "Best-Seller Pick",
      swipePrompt: "Next concept ➔",
    },
    {
      slideNumber: 3,
      type: "content",
      eyebrow: "02 · THE CONNOISSEUR'S DELIGHT",
      headline: "The Gourmet Epicurean & Tasting Box",
      subheadline: "Food is memory. A curated tasting hamper creates shared laughter.",
      body: "Skip grocery store snack packs. Combine single-origin raw wildflower honey, aged balsamic glaze, artisan pistachio brittle, and hand-carved olive wood bowls.",
      bulletPoints: [
        "Focus on shelf-stable artisan rarities they wouldn't buy themselves",
        "Include a pairing recipe card for an intimate evening",
        "Wrap with neutral linen ribbon and sprigs of dried eucalyptus"
      ],
      highlightBadge: "Crowd Favorite",
      swipePrompt: "Next concept ➔",
    },
    {
      slideNumber: 4,
      type: "content",
      eyebrow: "03 · THE SENTIMENTAL TREASURE",
      headline: "The Monogrammed Keepsake Hamper",
      subheadline: "Personalization transforms a good object into an heirloom.",
      body: "Combine a custom debossed leather journal or passport sleeve with customized stationery, artisan sealing wax, and a heartfelt dedication letter.",
      bulletPoints: [
        "Debossed initials add instant bespoke luxury",
        "Include date stamps or meaningful coordinates",
        "A gift they will carry for the next 10 years"
      ],
      highlightBadge: "High Sentiment",
      swipePrompt: "See full guide ➔",
    },
    {
      slideNumber: 5,
      type: "cta",
      eyebrow: "FIND YOUR NEXT SURPRISE",
      headline: "Explore Handcrafted Gifts & Hampers That Speak From The Heart",
      subheadline: "Discover bespoke gift boxes, personalized keepsakes, and fast doorstep delivery.",
      body: "Ready to make someone's day? Explore our full curated collection on our website and get ready to witness genuine unboxing joy.",
      bulletPoints: [
        "Save this carousel for your upcoming birthdays & anniversaries",
        "Share with a friend in need of gift inspiration",
        "Tap the link to explore the catalog: https://snazzy-gnome-1d4893.netlify.app/gifts"
      ],
      highlightBadge: "snazzy-gnome-1d4893.netlify.app/gifts",
      swipePrompt: "Visit the store ➔",
    },
  ],
  caption: `Struggling to find a present that actually feels personal and breathtaking? ✨

Most gift baskets end up sitting unopened in a kitchen corner because they lack soul. When you curate with intention—focusing on sensory textures, bespoke details, and heirloom keepsakes—the unboxing becomes an emotional experience.

Here are 3 of our favorite hamper concepts for this season:
🛁 01. The Artisan Spa & Restoration Sanctuary
🍯 02. The Gourmet Epicurean Tasting Box
🖋️ 03. The Monogrammed Keepsake Suite

Which one would you love to receive? Tell us in the comments! 👇

🎁 Discover hundreds of thoughtful, beautifully wrapped presents ready to surprise your loved ones:
👉 Visit: https://snazzy-gnome-1d4893.netlify.app/gifts

#giftideas #curatedhampers #luxurygifting #snazzygnome #birthdaygifts #anniversarygift #thoughtfulgifts #giftguide2026 #giftinspiration #bespokegifts #unboxingexperience`,
  hashtags: [
    "#giftideas",
    "#curatedhampers",
    "#luxurygifting",
    "#snazzygnome",
    "#birthdaygifts",
    "#anniversarygift",
    "#thoughtfulgifts",
    "#giftguide2026",
    "#bespokegifts"
  ],
  callToAction: "Explore Curated Gifts at https://snazzy-gnome-1d4893.netlify.app/gifts",
};
